messages:
  join: "&e&l>> &fWelcome to the serwer &a{PLAYER}!"
  quit: "&e&l>> &fSee you later &a{PLAYER}!"
  reload: "Plugin is correctly reload!"
  no-permission: "You don't have permissions!"
  usage: "Usage /cmm reload"

